services:
  update:
    build:
      dockerfile: Dockerfile.update
      context: .
    ports:
      - 8080:8080
  fix:
    build:
      dockerfile: Dockerfile.fix
      context: .
    ports:
      - 8080:8081
    depends_on:
      update:
        condition: service_started
